name: mpi-sppy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    container:
        image: davidwin87/cplex_trial_core_image:latest
        env:
	    PATH: /opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/bin/x86-64_linux:/usr/bin:/usr/opt

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y mpich
          pip install wheel
          python -m pip install --upgrade pip
          pip install pyomo pandas mpi4py
          python setup.py develop

      - name: run tests
        run: |
          python mpisspy/tests/test_ef_ph.py
