name: mpi-sppy (Pyomo released)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: davidwin87/cplex_trial_core_image:latest
        env:
          PATH: :/usr/local/bin:/usr/local/sbin:usr/sbin:/usr/bin:/sbin:/bin:/opt/ibm/ILOG/CPLEX_Studio_Community129/cplex/bin/x86-64_linux

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y mpich
          pip install wheel
          pip install --upgrade pip
          pip install pyomo pandas mpi4py setuptools sphinx

      - name: setup the program
        run: |
          python setup.py develop

      - name: Test EF/PH
        run: |
          python mpisppy/tests/test_ef_ph.py

      - name: Test afew
        run: |
          cd examples
          python afew.py cplex

      - name: Test docs
        run: |
          cd ./doc/src/
          make doctest
